language: python

python:
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y graphviz 

install:
  - "python setup.py install"
  - "pip install codecov"

script:
  - "coverage run tests/test_dafsa.py"

after_success:
  - "codecov"
